# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if (ENABLE_INFERENCE_TESTS)
    add_definitions(-DINFERENCE_TEST_DATA="${CMAKE_CURRENT_SOURCE_DIR}/testdata")

    function(add_nes_test_inference)
        add_nes_test(${ARGN})
        set(TARGET_NAME ${ARGV0})
        target_link_libraries(${TARGET_NAME} nes-inference)
        target_include_directories(${TARGET_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../src)
    endfunction()

    add_nes_test_inference(ModelLoaderTest ModelLoaderTest.cpp)
    add_nes_test_inference(ModelCatalogTest ModelCatalogTest.cpp)

    add_nes_test_inference(InferenceRuntimeTest InferenceRuntimeTest.cpp)
    target_link_libraries(InferenceRuntimeTest nes-inference-runtime)
    target_include_directories(InferenceRuntimeTest PRIVATE $<TARGET_PROPERTY:openvino::runtime,INTERFACE_INCLUDE_DIRECTORIES>)
endif ()
